///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace IOSTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the IOSTestRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("bf094d01-1d63-4f5c-9a80-d7dbb45fb09a")]
    public partial class IOSTestRepository : RepoGenBaseFolder
    {
        static IOSTestRepository instance = new IOSTestRepository();
        IOSTestRepositoryFolders.ComDigitalbarriersEdgeVisClientAppFolder _comdigitalbarriersedgevisclient;

        /// <summary>
        /// Gets the singleton class instance representing the IOSTestRepository element repository.
        /// </summary>
        [RepositoryFolder("bf094d01-1d63-4f5c-9a80-d7dbb45fb09a")]
        public static IOSTestRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public IOSTestRepository() 
            : base("IOSTestRepository", "/", null, 0, false, "bf094d01-1d63-4f5c-9a80-d7dbb45fb09a", ".\\RepositoryImages\\IOSTestRepositorybf094d01.rximgres")
        {
            _comdigitalbarriersedgevisclient = new IOSTestRepositoryFolders.ComDigitalbarriersEdgeVisClientAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("bf094d01-1d63-4f5c-9a80-d7dbb45fb09a")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ComDigitalbarriersEdgeVisClient folder.
        /// </summary>
        [RepositoryFolder("e8d0d8ac-7057-4926-8087-e17a4e82d090")]
        public virtual IOSTestRepositoryFolders.ComDigitalbarriersEdgeVisClientAppFolder ComDigitalbarriersEdgeVisClient
        {
            get { return _comdigitalbarriersedgevisclient; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class IOSTestRepositoryFolders
    {
        /// <summary>
        /// The ComDigitalbarriersEdgeVisClientAppFolder folder.
        /// </summary>
        [RepositoryFolder("e8d0d8ac-7057-4926-8087-e17a4e82d090")]
        public partial class ComDigitalbarriersEdgeVisClientAppFolder : RepoGenBaseFolder
        {
            IOSTestRepositoryFolders.UIWindowFolder _uiwindow;

            /// <summary>
            /// Creates a new ComDigitalbarriersEdgeVisClient  folder.
            /// </summary>
            public ComDigitalbarriersEdgeVisClientAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComDigitalbarriersEdgeVisClient", "/mobileapp[@title='com.digitalbarriers.EdgeVis-Client']", parentFolder, 30000, null, false, "e8d0d8ac-7057-4926-8087-e17a4e82d090", "")
            {
                _uiwindow = new IOSTestRepositoryFolders.UIWindowFolder(this);
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e8d0d8ac-7057-4926-8087-e17a4e82d090")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e8d0d8ac-7057-4926-8087-e17a4e82d090")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UIWindow folder.
            /// </summary>
            [RepositoryFolder("5a6ba6e9-6b56-4aca-9b52-f7681c3d71bc")]
            public virtual IOSTestRepositoryFolders.UIWindowFolder UIWindow
            {
                get { return _uiwindow; }
            }
        }

        /// <summary>
        /// The UIWindowFolder folder.
        /// </summary>
        [RepositoryFolder("5a6ba6e9-6b56-4aca-9b52-f7681c3d71bc")]
        public partial class UIWindowFolder : RepoGenBaseFolder
        {
            RepoItemInfo _click_manageInfo;
            RepoItemInfo _click_editInfo;
            RepoItemInfo _enter_usernameInfo;
            RepoItemInfo _enter_passwordInfo;
            RepoItemInfo _click_saveInfo;
            RepoItemInfo _connect_clickInfo;
            RepoItemInfo _buttonok_clickInfo;
            RepoItemInfo _click_alerticonenabledInfo;
            RepoItemInfo _click_mapiconenabledInfo;
            RepoItemInfo _viewoptions_rightInfo;
            RepoItemInfo _password2_clickInfo;
            RepoItemInfo _connectInfo;
            RepoItemInfo _logouttestaInfo;
            RepoItemInfo _validation_edgevisclientInfo;

            /// <summary>
            /// Creates a new UIWindow  folder.
            /// </summary>
            public UIWindowFolder(RepoGenBaseFolder parentFolder) :
                    base("UIWindow", "form", parentFolder, 30000, null, false, "5a6ba6e9-6b56-4aca-9b52-f7681c3d71bc", "")
            {
                _click_manageInfo = new RepoItemInfo(this, "Click_MANAGE", ".//container[@containertype='ViewControllerWrapper']/container/container[3]/?/?/button[@accessibilitylabel='MANAGE']", 30000, null, "d4575e4d-e495-4ea6-88d0-ec6b34ed1327");
                _click_editInfo = new RepoItemInfo(this, "Click_EDIT", ".//container[@containertype='ViewControllerWrapper']/container/container[3]/table/container[1]//button[@accessibilitylabel='EDIT']", 30000, null, "c397d789-48c6-4589-afbb-e884dfbbd729");
                _enter_usernameInfo = new RepoItemInfo(this, "Enter_Username", "container[1]/?/?/container[@containertype='ViewControllerWrapper']/container/container[1]//container[@containertype='ViewControllerWrapper']/container/text[3]", 30000, null, "19769af7-0a99-498c-86b6-134d15945704");
                _enter_passwordInfo = new RepoItemInfo(this, "Enter_Password", "container[1]/?/?/container[@containertype='ViewControllerWrapper']/container/container[1]//container[@containertype='ViewControllerWrapper']/container/text[5]", 30000, null, "72b9a674-1678-47c0-af7d-730c8de1670d");
                _click_saveInfo = new RepoItemInfo(this, "Click_SAVE", "container[1]/?/?/container[@containertype='ViewControllerWrapper']/container/container[1]//container[@containertype='ViewControllerWrapper']/?/?/button[@accessibilitylabel='SAVE']", 30000, null, "060e6600-beb0-41d3-8b6e-7eb4b7b39528");
                _connect_clickInfo = new RepoItemInfo(this, "CONNECT_Click", ".//container[@containertype='ViewControllerWrapper']/container/container[3]/table/container[1]//button[@accessibilitylabel='CONNECT']", 30000, null, "5bf0e370-3c2b-44fa-ae6a-c7d69700684f");
                _buttonok_clickInfo = new RepoItemInfo(this, "ButtonOK_Click", "container[1]/container[@containertype='']/container[@caption='']/container[@caption='']/container[@caption='']/container[4]/button[@accessibilitylabel='OK']", 30000, null, "7c334632-ff74-4fe0-bc80-f4fb68e19676");
                _click_alerticonenabledInfo = new RepoItemInfo(this, "Click_AlertIconEnabled", "?/?/container[@containertype='LayoutContainer']/container[@caption='']/container/container[@caption='']/container[1]/?/?/button[@accessibilitylabel='Alert icon enabled']", 30000, null, "a1ef10e7-e705-4e8a-8c5c-49ef72ff885f");
                _click_mapiconenabledInfo = new RepoItemInfo(this, "Click_MapIconEnabled", "?/?/container[@containertype='LayoutContainer']/container[@caption='']/container/container[@caption='']/container[1]/?/?/button[@accessibilitylabel='Map icon enabled']", 30000, null, "b07bbfaf-bdae-4d4d-955a-a49a9f3d3586");
                _viewoptions_rightInfo = new RepoItemInfo(this, "ViewOptions_Right", "?/?/container[@containertype='LayoutContainer']/container[@caption='']/container/container[@caption='']/container[1]/?/?/button[@accessibilitylabel='HotDog icon enabled']", 30000, null, "16b96087-29c9-4b13-afd3-e03fe6e5b17d");
                _password2_clickInfo = new RepoItemInfo(this, "Password2_Click", "container[1]/?/?/container[@containertype='ViewControllerWrapper']/container/container[1]//container[@containertype='ViewControllerWrapper']/container/text[4]", 30000, null, "ab4612c8-3a80-46fb-982a-7a20f0d49f73");
                _connectInfo = new RepoItemInfo(this, "CONNECT", "container[1]/?/?/container[@containertype='ViewControllerWrapper']/container/container[1]//container[@containertype='ViewControllerWrapper']/?/?/button[@accessibilitylabel='CONNECT']", 30000, null, "239e6e7d-53e2-4b50-b2b7-2b53e45cca70");
                _logouttestaInfo = new RepoItemInfo(this, "LogOutTestA", ".//table/?/?/cell[@accessibilitylabel='Log out TestA']/text[@accessibilitylabel='Log out TestA']", 30000, null, "f3201539-4a7b-4841-8b3d-c842e99db5cd");
                _validation_edgevisclientInfo = new RepoItemInfo(this, "Validation_EdgeVisClient", "container[1]/container[@containertype='']", 30000, null, "7e752ff6-334a-4cdf-b57a-b165012a3f60");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("5a6ba6e9-6b56-4aca-9b52-f7681c3d71bc")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("5a6ba6e9-6b56-4aca-9b52-f7681c3d71bc")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Click_MANAGE item.
            /// </summary>
            [RepositoryItem("d4575e4d-e495-4ea6-88d0-ec6b34ed1327")]
            public virtual Ranorex.Button Click_MANAGE
            {
                get
                {
                    return _click_manageInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Click_MANAGE item info.
            /// </summary>
            [RepositoryItemInfo("d4575e4d-e495-4ea6-88d0-ec6b34ed1327")]
            public virtual RepoItemInfo Click_MANAGEInfo
            {
                get
                {
                    return _click_manageInfo;
                }
            }

            /// <summary>
            /// The Click_EDIT item.
            /// </summary>
            [RepositoryItem("c397d789-48c6-4589-afbb-e884dfbbd729")]
            public virtual Ranorex.Button Click_EDIT
            {
                get
                {
                    return _click_editInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Click_EDIT item info.
            /// </summary>
            [RepositoryItemInfo("c397d789-48c6-4589-afbb-e884dfbbd729")]
            public virtual RepoItemInfo Click_EDITInfo
            {
                get
                {
                    return _click_editInfo;
                }
            }

            /// <summary>
            /// The Enter_Username item.
            /// </summary>
            [RepositoryItem("19769af7-0a99-498c-86b6-134d15945704")]
            public virtual Ranorex.Text Enter_Username
            {
                get
                {
                    return _enter_usernameInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Enter_Username item info.
            /// </summary>
            [RepositoryItemInfo("19769af7-0a99-498c-86b6-134d15945704")]
            public virtual RepoItemInfo Enter_UsernameInfo
            {
                get
                {
                    return _enter_usernameInfo;
                }
            }

            /// <summary>
            /// The Enter_Password item.
            /// </summary>
            [RepositoryItem("72b9a674-1678-47c0-af7d-730c8de1670d")]
            public virtual Ranorex.Text Enter_Password
            {
                get
                {
                    return _enter_passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Enter_Password item info.
            /// </summary>
            [RepositoryItemInfo("72b9a674-1678-47c0-af7d-730c8de1670d")]
            public virtual RepoItemInfo Enter_PasswordInfo
            {
                get
                {
                    return _enter_passwordInfo;
                }
            }

            /// <summary>
            /// The Click_SAVE item.
            /// </summary>
            [RepositoryItem("060e6600-beb0-41d3-8b6e-7eb4b7b39528")]
            public virtual Ranorex.Button Click_SAVE
            {
                get
                {
                    return _click_saveInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Click_SAVE item info.
            /// </summary>
            [RepositoryItemInfo("060e6600-beb0-41d3-8b6e-7eb4b7b39528")]
            public virtual RepoItemInfo Click_SAVEInfo
            {
                get
                {
                    return _click_saveInfo;
                }
            }

            /// <summary>
            /// The CONNECT_Click item.
            /// </summary>
            [RepositoryItem("5bf0e370-3c2b-44fa-ae6a-c7d69700684f")]
            public virtual Ranorex.Button CONNECT_Click
            {
                get
                {
                    return _connect_clickInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CONNECT_Click item info.
            /// </summary>
            [RepositoryItemInfo("5bf0e370-3c2b-44fa-ae6a-c7d69700684f")]
            public virtual RepoItemInfo CONNECT_ClickInfo
            {
                get
                {
                    return _connect_clickInfo;
                }
            }

            /// <summary>
            /// The ButtonOK_Click item.
            /// </summary>
            [RepositoryItem("7c334632-ff74-4fe0-bc80-f4fb68e19676")]
            public virtual Ranorex.Button ButtonOK_Click
            {
                get
                {
                    return _buttonok_clickInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK_Click item info.
            /// </summary>
            [RepositoryItemInfo("7c334632-ff74-4fe0-bc80-f4fb68e19676")]
            public virtual RepoItemInfo ButtonOK_ClickInfo
            {
                get
                {
                    return _buttonok_clickInfo;
                }
            }

            /// <summary>
            /// The Click_AlertIconEnabled item.
            /// </summary>
            [RepositoryItem("a1ef10e7-e705-4e8a-8c5c-49ef72ff885f")]
            public virtual Ranorex.Button Click_AlertIconEnabled
            {
                get
                {
                    return _click_alerticonenabledInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Click_AlertIconEnabled item info.
            /// </summary>
            [RepositoryItemInfo("a1ef10e7-e705-4e8a-8c5c-49ef72ff885f")]
            public virtual RepoItemInfo Click_AlertIconEnabledInfo
            {
                get
                {
                    return _click_alerticonenabledInfo;
                }
            }

            /// <summary>
            /// The Click_MapIconEnabled item.
            /// </summary>
            [RepositoryItem("b07bbfaf-bdae-4d4d-955a-a49a9f3d3586")]
            public virtual Ranorex.Button Click_MapIconEnabled
            {
                get
                {
                    return _click_mapiconenabledInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Click_MapIconEnabled item info.
            /// </summary>
            [RepositoryItemInfo("b07bbfaf-bdae-4d4d-955a-a49a9f3d3586")]
            public virtual RepoItemInfo Click_MapIconEnabledInfo
            {
                get
                {
                    return _click_mapiconenabledInfo;
                }
            }

            /// <summary>
            /// The ViewOptions_Right item.
            /// </summary>
            [RepositoryItem("16b96087-29c9-4b13-afd3-e03fe6e5b17d")]
            public virtual Ranorex.Button ViewOptions_Right
            {
                get
                {
                    return _viewoptions_rightInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ViewOptions_Right item info.
            /// </summary>
            [RepositoryItemInfo("16b96087-29c9-4b13-afd3-e03fe6e5b17d")]
            public virtual RepoItemInfo ViewOptions_RightInfo
            {
                get
                {
                    return _viewoptions_rightInfo;
                }
            }

            /// <summary>
            /// The Password2_Click item.
            /// </summary>
            [RepositoryItem("ab4612c8-3a80-46fb-982a-7a20f0d49f73")]
            public virtual Ranorex.Text Password2_Click
            {
                get
                {
                    return _password2_clickInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password2_Click item info.
            /// </summary>
            [RepositoryItemInfo("ab4612c8-3a80-46fb-982a-7a20f0d49f73")]
            public virtual RepoItemInfo Password2_ClickInfo
            {
                get
                {
                    return _password2_clickInfo;
                }
            }

            /// <summary>
            /// The CONNECT item.
            /// </summary>
            [RepositoryItem("239e6e7d-53e2-4b50-b2b7-2b53e45cca70")]
            public virtual Ranorex.Button CONNECT
            {
                get
                {
                    return _connectInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CONNECT item info.
            /// </summary>
            [RepositoryItemInfo("239e6e7d-53e2-4b50-b2b7-2b53e45cca70")]
            public virtual RepoItemInfo CONNECTInfo
            {
                get
                {
                    return _connectInfo;
                }
            }

            /// <summary>
            /// The LogOutTestA item.
            /// </summary>
            [RepositoryItem("f3201539-4a7b-4841-8b3d-c842e99db5cd")]
            public virtual Ranorex.Text LogOutTestA
            {
                get
                {
                    return _logouttestaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The LogOutTestA item info.
            /// </summary>
            [RepositoryItemInfo("f3201539-4a7b-4841-8b3d-c842e99db5cd")]
            public virtual RepoItemInfo LogOutTestAInfo
            {
                get
                {
                    return _logouttestaInfo;
                }
            }

            /// <summary>
            /// The Validation_EdgeVisClient item.
            /// </summary>
            [RepositoryItem("7e752ff6-334a-4cdf-b57a-b165012a3f60")]
            public virtual Ranorex.Container Validation_EdgeVisClient
            {
                get
                {
                    return _validation_edgevisclientInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Validation_EdgeVisClient item info.
            /// </summary>
            [RepositoryItemInfo("7e752ff6-334a-4cdf-b57a-b165012a3f60")]
            public virtual RepoItemInfo Validation_EdgeVisClientInfo
            {
                get
                {
                    return _validation_edgevisclientInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
