///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace IOSTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Validation_EdgeVisClient recording.
    /// </summary>
    [TestModule("fe37ea9e-244d-4fcf-931b-be1961ca9172", ModuleType.Recording, 1)]
    public partial class Validation_EdgeVisClient : ITestModule
    {
        /// <summary>
        /// Holds an instance of the IOSTestRepository repository.
        /// </summary>
        public static IOSTestRepository repo = IOSTestRepository.Instance;

        static Validation_EdgeVisClient instance = new Validation_EdgeVisClient();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Validation_EdgeVisClient()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Validation_EdgeVisClient Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'ComDigitalbarriersEdgeVisClient.UIWindow.Validation_EdgeVisClient'.", repo.ComDigitalbarriersEdgeVisClient.UIWindow.Validation_EdgeVisClientInfo, new RecordItemIndex(0));
            Validate.Exists(repo.ComDigitalbarriersEdgeVisClient.UIWindow.Validation_EdgeVisClientInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
